# Generated by Django 5.2.4 on 2025-10-26 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_store_user_stores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="stores",
        ),
        migrations.AddField(
            model_name="user",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="core.store",
            ),
        ),
    ]
