# Generated by Django 5.2.4 on 2025-07-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="check_in_photo",
            field=models.ImageField(blank=True, null=True, upload_to="checkin_photos/"),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="checkout_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_photos/"
            ),
        ),
    ]
