# Generated by Django 5.2.4 on 2025-07-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employee",
            "0002_attendance_check_in_photo_attendance_check_out_photo_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="payroll",
            old_name="created_at",
            new_name="paid_at",
        ),
        migrations.RemoveField(
            model_name="payroll",
            name="amount_paid",
        ),
        migrations.AddField(
            model_name="payroll",
            name="period_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payroll",
            name="period_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payroll",
            name="total_paid",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
