# Generated by Django 5.2.4 on 2025-08-09 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_rename_created_at_payroll_paid_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="current_balance",
        ),
        migrations.AddField(
            model_name="attendance",
            name="payroll",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendances",
                to="employee.payroll",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
