# Generated by Django 5.2.4 on 2025-08-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employee",
            "0004_remove_employee_current_balance_attendance_payroll_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payroll",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
