# Generated by Django 5.2.4 on 2025-10-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_store_user_stores"),
        ("employee", "0005_alter_payroll_paid_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="stores",
            field=models.ManyToManyField(
                blank=True, related_name="employees", to="core.store"
            ),
        ),
    ]
