# Generated by Django 5.2.4 on 2025-11-22 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_user_stores_user_store"),
        ("employee", "0007_remove_employee_stores"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.store",
            ),
        ),
    ]
