# Generated by Django 4.2.23 on 2025-07-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="smoothieingredient",
            unique_together={("smoothie", "ingredient")},
        ),
    ]
