# Generated by Django 5.2.4 on 2025-07-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="smoothieingredient",
            unique_together={("smoothie", "ingredient")},
        ),
    ]
