<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-07-28 13:58
=======
# Generated by Django 4.2.23 on 2025-07-28 14:34
>>>>>>> 0b20f49a93e60663861f1786019d35fbc04fbc20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="smoothieingredient",
            unique_together={("smoothie", "ingredient")},
        ),
    ]
