# Generated by Django 5.2.4 on 2025-08-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_smoothieingredient_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="usable_proportion",
            field=models.FloatField(default=1.0),
        ),
    ]
