# Generated by Django 5.2.4 on 2025-08-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_ingredient_usable_proportion"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="usable_stock",
            field=models.FloatField(default=0),
        ),
    ]
