# Generated by Django 5.2.4 on 2025-08-05 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_ingredient_usable_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="usable_proportion",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="usable_stock",
        ),
    ]
