# Generated by Django 5.2.4 on 2025-08-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_remove_ingredient_usable_proportion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockentry",
            name="reason",
            field=models.CharField(
                choices=[
                    ("manual_add", "Manual Addition"),
                    ("manual_deduct", "Manual Deduction"),
                    ("sale_deduct", "Sale Deduction"),
                    ("sale_cancellation", "Sale Cancellation"),
                ],
                max_length=100,
            ),
        ),
    ]
