# Generated by Django 5.2.4 on 2025-10-26 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_store_user_stores"),
        ("inventory", "0006_alter_stockentry_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="core.store",
            ),
        ),
    ]
