# Generated by Django 5.2.4 on 2025-11-22 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_user_stores_user_store"),
        ("inventory", "0007_ingredient_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="smoothieingredient",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="smoothie_ingredients",
                to="core.store",
            ),
        ),
        migrations.AddField(
            model_name="smoothiemenu",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="smoothie_menus",
                to="core.store",
            ),
        ),
        migrations.AddField(
            model_name="stockentry",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_entries",
                to="core.store",
            ),
        ),
    ]
