# Generated by Django 5.2.4 on 2025-11-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_user_stores_user_store"),
        ("inventory", "0008_smoothieingredient_store_smoothiemenu_store_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smoothieingredient",
            name="store",
        ),
        migrations.RemoveField(
            model_name="smoothiemenu",
            name="store",
        ),
        migrations.RemoveField(
            model_name="stockentry",
            name="store",
        ),
        migrations.AddField(
            model_name="smoothiemenu",
            name="stores",
            field=models.ManyToManyField(
                related_name="smoothie_menus", to="core.store"
            ),
        ),
    ]
