# Generated by Django 5.2.4 on 2025-08-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
