# Generated by Django 4.2.23 on 2025-07-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("qris", "QRIS")],
                default="qris",
                max_length=10,
            ),
        ),
    ]
