# Generated by Django 5.2.4 on 2025-08-02 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customer_phone"),
        ("sales", "0003_order_created_at_order_is_ready_order_is_served_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customers.customer",
            ),
        ),
    ]
